apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-znn
  labels:
    app: kube-znn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-znn
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "25%"
      maxSurge: "25%"
  template:
    metadata:
      labels:
        app: kube-znn
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9145"
    spec:
      nodeSelector:
        autoscaling.lab/app: "yes"
      volumes:
        - name: shared-files
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      containers:
        - image: registry.k8s.lab/znn:600k
          imagePullPolicy: Always
          name: znn
          env:
            - name: DB_HOST
              value: "kube-znn-db"
            - name: DB_NAME
              value: "znn"
            - name: DB_PASS
              value: "znn_pass"
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
          ports:
            - name: fpm
              containerPort: 9000
          resources:
            requests:
              cpu: "50m"
              memory: "16Mi"
            limits:
              cpu: "150m"
              memory: "64Mi"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /www/. /var/www/html"]
        - image: openresty/openresty:alpine-fat
          name: nginx
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
            - name: nginx-config-volume
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx-lua-prometheus/prometheus_resty_counter.lua
              subPath: prometheus_resty_counter.lua
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx-lua-prometheus/prometheus_keys.lua
              subPath: prometheus_keys.lua
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx-lua-prometheus/prometheus.lua
              subPath: prometheus.lua
          ports:
            - name: http
              containerPort: 80
            - name: exporter
              containerPort: 9145
          resources:
            requests:
              cpu: "50m"
              memory: "16Mi"
            limits:
              cpu: "150m"
              memory: "64Mi"
