apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-znn
  labels:
    name: kube-znn
spec:
  ingressClassName: "nginx"
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kube-znn
            port:
              name: http
