apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-znn
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchLabels:
      app: kube-znn
  endpoints:
    - port: exporter
      path: /metrics
      scheme: http
      interval: 5s
      scrapeTimeout: 1s
